package tui

import (
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/rivo/uniseg"
)

// StrWidth returns the display width of s the way ratatui measures a
// span/line (unicode-width 0.2 `str::width`): the sum of the widths of its
// grapheme clusters. Unlike summing RuneWidth, this counts emoji ZWJ
// sequences, flags, VS16 sequences and Hangul jamo clusters once, and
// counts control characters as 1.
func StrWidth(s string) int {
	w := 0
	for i := 0; i < len(s); {
		if b := s[i]; b < utf8.RuneSelf && (i+1 == len(s) || s[i+1] < utf8.RuneSelf) && b != '\r' {
			// ASCII followed by ASCII: always its own grapheme of width 1.
			w++
			i++
			continue
		}
		g, rest, _, _ := uniseg.FirstGraphemeClusterInString(s[i:], -1)
		w += GraphemeWidth(g)
		i = len(s) - len(rest)
	}
	return w
}

// RuneWidth returns the display width of a single rune. Control characters
// have no width.
func RuneWidth(r rune) int {
	if r < 0x20 || (r >= 0x7f && r < 0xa0) {
		return 0
	}
	return uniseg.StringWidth(string(r))
}

// GraphemeWidth returns the display width of a single grapheme cluster as
// ratatui computes it (unicode-width 0.2 `str::width` of the grapheme).
// Inside strings unicode-width counts every code point up to U+00A0
// (including control characters such as '\t') as 1 and "\r\n" as 1; a few
// code points differ between uniseg and unicode-width 0.2 and are corrected
// via strWidthOverrides.
func GraphemeWidth(g string) int {
	if g == "" {
		return 0
	}
	if len(g) == 1 {
		return 1 // ASCII, including control characters
	}
	if g == "\r\n" {
		return 1
	}
	if r, n := utf8.DecodeRuneInString(g); n == len(g) {
		return codepointStrWidth(r)
	}
	// Keycap sequences ([0-9#*] U+FE0F U+20E3) are wide in unicode-width.
	if len(g) == 7 && strings.HasSuffix(g, "\ufe0f\u20e3") {
		switch g[0] {
		case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '#', '*':
			return 2
		}
	}
	if isEmojiCluster(g) {
		return uniseg.StringWidth(g)
	}
	// Outside emoji sequences unicode-width simply sums the code points'
	// widths (combining marks are zero width, spacing marks are not).
	w := 0
	for _, r := range g {
		w += codepointStrWidth(r)
	}
	return w
}

// isEmojiCluster reports whether g uses emoji machinery (presentation
// selectors, ZWJ, keycaps, regional indicators, skin tones or tags); such
// clusters are measured by uniseg.
func isEmojiCluster(g string) bool {
	for _, r := range g {
		switch {
		case r == 0xfe0e, r == 0xfe0f, r == 0x200d, r == 0x20e3,
			r >= 0x1f1e6 && r <= 0x1f1ff,
			r >= 0x1f3fb && r <= 0x1f3ff,
			r >= 0xe0020 && r <= 0xe007f:
			return true
		}
	}
	return false
}

// codepointStrWidth is the width unicode-width 0.2 gives r inside a string
// when no special sequence applies.
func codepointStrWidth(r rune) int {
	if r <= 0xa0 {
		return 1
	}
	if w, ok := strWidthOverride(r); ok {
		return w
	}
	return uniseg.StringWidth(string(r))
}

// strWidthOverrides lists the code points (above U+00A0) whose width in
// unicode-width 0.2.0 differs from uniseg's: {first, last, width}. The list
// was generated by comparing both libraries over every code point.
var strWidthOverrides = [...][3]int32{
	{0x0605, 0x0605, 0}, {0x070F, 0x070F, 0}, {0x0890, 0x0891, 0}, {0x08E2, 0x08E2, 0},
	{0x0CC0, 0x0CC0, 0}, {0x0CC7, 0x0CC8, 0}, {0x0CCA, 0x0CCB, 0}, {0x0D4E, 0x0D4E, 0},
	{0x1160, 0x11FF, 0}, {0x17A4, 0x17A4, 2}, {0x17D8, 0x17D8, 3}, {0x1B3B, 0x1B3B, 0},
	{0x1B3D, 0x1B3D, 0}, {0x1B43, 0x1B43, 0}, {0x2028, 0x2029, 1}, {0x2D7F, 0x2D7F, 1},
	{0x2E3A, 0x2E3A, 1}, {0x2E3B, 0x2E3B, 1}, {0x2FFC, 0x2FFF, 2}, {0x3030, 0x3030, 2},
	{0x303D, 0x303D, 2}, {0x3164, 0x3164, 0}, {0x31EF, 0x31EF, 2}, {0x3297, 0x3297, 2},
	{0x3299, 0x3299, 2}, {0xA8FA, 0xA8FA, 0}, {0xD7B0, 0xD7C6, 0}, {0xD7CB, 0xD7FB, 0},
	{0xFFA0, 0xFFA0, 0}, {0xFFF9, 0xFFFB, 1}, {0x111C2, 0x111C3, 0}, {0x1193F, 0x1193F, 0},
	{0x11941, 0x11941, 0}, {0x11A3A, 0x11A3A, 0}, {0x11A84, 0x11A89, 0}, {0x11D46, 0x11D46, 0},
	{0x11F02, 0x11F02, 0}, {0x13430, 0x1343F, 1}, {0x1F1E6, 0x1F1FF, 1}, {0x1F202, 0x1F202, 2},
	{0x1F237, 0x1F237, 2}, {0x1F260, 0x1F265, 2}, {0x1F3FB, 0x1F3FF, 2},
}

func strWidthOverride(r rune) (int, bool) {
	if r < 0x0605 {
		return 0, false
	}
	lo, hi := 0, len(strWidthOverrides)
	for lo < hi {
		m := (lo + hi) / 2
		e := strWidthOverrides[m]
		switch {
		case r < e[0]:
			hi = m
		case r > e[1]:
			lo = m + 1
		default:
			return int(e[2]), true
		}
	}
	return 0, false
}

// Graphemes splits s into extended grapheme clusters.
func Graphemes(s string) []string {
	out := make([]string, 0, len(s))
	state := -1
	for s != "" {
		var g string
		g, s, state = NextGrapheme(s, state)
		out = append(out, g)
	}
	return out
}

// NextGrapheme returns the first extended grapheme cluster of s and the
// remainder, without allocating. Pass -1 as the initial state. Runs of ASCII
// take a fast path: between two ASCII characters there is always a cluster
// boundary except inside "\r\n".
func NextGrapheme(s string, state int) (g, rest string, newState int) {
	if len(s) == 1 && s[0] < utf8.RuneSelf {
		return s, "", -1
	}
	if len(s) > 1 && s[0] < utf8.RuneSelf && s[1] < utf8.RuneSelf {
		if s[0] == '\r' && s[1] == '\n' {
			return s[:2], s[2:], -1
		}
		return s[:1], s[1:], -1
	}
	g, rest, _, newState = uniseg.FirstGraphemeClusterInString(s, state)
	return g, rest, newState
}

// HasControl reports whether s contains a control character.
func HasControl(s string) bool {
	if len(s) == 1 {
		return s[0] < 0x20 || s[0] == 0x7f
	}
	for _, r := range s {
		if unicode.IsControl(r) {
			return true
		}
	}
	return false
}

// IsWhitespace reports whether every rune in s is whitespace.
func IsWhitespace(s string) bool {
	for _, r := range s {
		if !unicode.IsSpace(r) {
			return false
		}
	}
	return true
}
